# Database
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant_db
spring.datasource.username=root
spring.datasource.password=10203040
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.main.allow-circular-references=true

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8080


ai.default-response="Sorry, I couldn't understand that. Try asking about menu, veg, non-veg or specific dishes."

# JWT
jwt.secret=mySecretKeyForJWTTokenSigning1234567890abcdefghijklmnopqrstuvwxyz











